export const CHANGE_TAB = 'CHANGE_TAB';
export const UPDATE_FILTERED_TASKS = 'UPDATE_FILTERED_TASKS';

export const ADD_TASK = 'ADD_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
export const UPDATE_TASK_STATUS = 'UPDATE_TASK_STATUS';
export const SEARCH_TASKS = 'SEARCH_TASKS';
